// <auto-generated />
using System;
using MalaebBooking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MalaebBooking.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319151851_addrolepermissions")]
    partial class addrolepermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MalaebBooking.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297",
                            ConcurrencyStamp = "d1c8e5b9-9f0a-4c3e-8a1b-2f5e6d7c8a9b",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b9a61ca4-01bb-4a4f-8ccc-ca5dd59b42f9",
                            ConcurrencyStamp = "f3a7b8c9-0d2e-4f5a-9b3c-4d6e7f8a9b1c",
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        },
                        new
                        {
                            Id = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4",
                            ConcurrencyStamp = "e2f9c6a7-8b1d-4c3e-9a2b-3f6d7c8a9b0c",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        });
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "877a5585-4894-4f4b-8989-f45476063ce1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a25eba83-ab00-408b-8dfa-ce8a1cf37bea",
                            Email = "Admin@Malaeb-Booking.com",
                            EmailConfirmed = true,
                            FirstName = "Malaeb",
                            IsDisabled = false,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MALAEB-BOOKING.COM",
                            NormalizedUserName = "ADMIN@MALAEB-BOOKING.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBu6H7C9iF9Tq3twVRr0uJaFzrtfpWgkhEKBHa0jsAD+KuMRutaglQhMbnbICcDKyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "CFFCC4EEB0EE4D608E7CEFFE61FFDBD2",
                            TwoFactorEnabled = false,
                            UserName = "Admin@Malaeb-Booking.com"
                        });
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TimeSlotId")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentScreenshotUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlayerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.SportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SportTypes");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstapayNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("SportTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SportTypeId");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.StadiumImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("StadiumImages");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId", "Date", "StartTime")
                        .IsUnique();

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ViewProfile",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.UpdateProfile",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ChangePassword",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ViewAll",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ManageRoles",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.ToggleActive",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.Upload",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.SportTypes.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.SportTypes.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.SportTypes.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.SportTypes.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.SportTypes.UploadIcon",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.UpdateStatus",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Cancel",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.SubmitProof",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Approve",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Reject",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Reviews.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Reviews.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Reviews.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Reviews.Delete",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.View",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.Create",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.Update",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Roles.ToggleActive",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ViewProfile",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.UpdateProfile",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Users.ChangePassword",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.View",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 46,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.Create",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 47,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.Update",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 48,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Stadiums.ToggleActive",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 49,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.View",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.Upload",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.Update",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.StadiumImages.Delete",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.View",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.Create",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.Update",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.TimeSlots.Delete",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.View",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.UpdateStatus",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Bookings.Cancel",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.View",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Approve",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Payments.Reject",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "Permissions",
                            ClaimValue = "Permissions.Reviews.View",
                            RoleId = "5ab3a4d8-f2ee-48df-b897-a69fa5ef88d4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "877a5585-4894-4f4b-8989-f45476063ce1",
                            RoleId = "3a6ce7a1-2b66-48dd-ba28-3cf7080a3297"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.ApplicationUser", b =>
                {
                    b.OwnsMany("MalaebBooking.Domain.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationUser", "Player")
                        .WithMany("Bookings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MalaebBooking.Domain.Entities.TimeSlot", "TimeSlot")
                        .WithOne("Booking")
                        .HasForeignKey("MalaebBooking.Domain.Entities.Booking", "TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("MalaebBooking.Domain.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Review", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationUser", "Player")
                        .WithMany("Reviews")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MalaebBooking.Domain.Entities.Stadium", "Stadium")
                        .WithMany("Reviews")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Stadium", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany("OwnedStadiums")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MalaebBooking.Domain.Entities.SportType", "SportType")
                        .WithMany("Stadiums")
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.StadiumImage", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.Stadium", "Stadium")
                        .WithMany("Images")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.TimeSlot", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.Stadium", "Stadium")
                        .WithMany("TimeSlots")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MalaebBooking.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("OwnedStadiums");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.SportType", b =>
                {
                    b.Navigation("Stadiums");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.Stadium", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("MalaebBooking.Domain.Entities.TimeSlot", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
